services:
  library:
    image: library_app 
    build: .
    depends_on :
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python library/manage.py migrate &&
             python library/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
